name: Build and Push updated Docker Image
on: push
jobs:
  build-container:
    name: Build Docker Container Image
    runs-on: ubuntu-latest
    steps:
    - name: Enter Packages Directory
      run: cd packages
      
    - name: Enter Source Directory
      run: cd enketo-express
      
    - name: Build Docker Image
      run: docker build -t docker.pkg.github.com/Ansh-Sarkar/workflow/enketo-express:latest .
