name: Build and Push updated Docker Image
on: push
jobs:
  build-container:
    name: Build Docker Container Image
    runs-on: ubuntu-latest
    steps:
    - name: Build Docker image
      run: ls && cd packages/enketo-express && docker build -t docker.pkg.github.com/${{ env.GITHUB_REPOSITORY }}/enketo-express:latest .
